targets:
  $default:
    builders:
      freezed:
        options:
          map: false
          when: false
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - strict_raw_type
            - type=lint
